name = "gram_server"
author = "andrew"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "570d154a3b4eff4bb90e24eebfb5aab5657fd50eb92837f3fd2bfabfac96b64d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
