name = "gram_server"
author = "andrew"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9aa33f3709558bb4686b845bf98b5790ba8a3e64a176080fccd008992ab2f2e6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
