name = "gram_server"
author = "andrew"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "64cd0f7a464028567a2885421f947fa1340c2d0e79e5134907764b99eb08e3de"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
